# Config for Dependabot updates. See Documentation here:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: github-actions
    directory: /
    # Every weekday
    schedule:
      interval: daily

  # Update npm packages
  - package-ecosystem: npm
    directories:
      - /
      - /apps/*
      - /packages/*
    groups:
      definitely-typed:
        patterns:
          - "@types*"
        update-types:
          - minor
          - patch
      commitlint:
        patterns:
          - "@commitlint*"
    # Every weekday
    schedule:
      interval: daily
